package dev.dertyp.rpc.doc

import com.google.devtools.ksp.isPublic
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.validate
import java.io.File
import java.io.OutputStream

class DocProcessor(
    private val options: Map<String, String>
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val serviceSymbols = resolver.getSymbolsWithAnnotation("dev.dertyp.rpc.annotations.RpcDoc")
            .filterIsInstance<KSClassDeclaration>()
            .toList()

        val modelSymbols = resolver.getSymbolsWithAnnotation("dev.dertyp.rpc.annotations.ModelDoc")
            .filterIsInstance<KSClassDeclaration>()
            .toList()

        if (serviceSymbols.isEmpty() && modelSymbols.isEmpty()) return emptyList()

        val anySourceFile = (serviceSymbols.firstOrNull() ?: modelSymbols.firstOrNull())?.containingFile?.filePath ?: return emptyList()

        val projectRoot = findProjectRoot(File(anySourceFile))
        
        val docPath = options["rpc.doc.path"] ?: "docs"
        val docName = options["rpc.doc.name"] ?: "RPC_SERVICES.md"
        
        val docsDir = if (docPath.startsWith("/")) File(docPath) else File(projectRoot, docPath)
        if (!docsDir.exists()) docsDir.mkdirs()
        val docFile = File(docsDir, docName)

        val documentedModels = modelSymbols.mapNotNull { it.qualifiedName?.asString() }.toSet()
        val duplicateNames = (modelSymbols + serviceSymbols).groupBy { it.simpleName.asString() }.filter { it.value.size > 1 }.keys

        docFile.outputStream().use { out ->
            out.writeLine("# Synara RPC Services Documentation")
            out.writeLine("")
            out.writeLine("This document is automatically generated by the DocProcessor KSP.")
            out.writeLine("")

            out.writeLine("## Table of Contents")
            out.writeLine("- [Data Models](#data-models)")
            modelSymbols.sortedBy { it.qualifiedName?.asString() }.forEach { model ->
                val name = model.simpleName.asString()
                val qName = model.qualifiedName?.asString() ?: name
                val anchor = qName.lowercase().replace(".", "")
                val displayName = if (name in duplicateNames) qName else name
                out.writeLine("    - [$displayName](#$anchor)")
            }
            out.writeLine("- [RPC Services](#rpc-services)")
            serviceSymbols.sortedBy { it.qualifiedName?.asString() }.forEach { symbol ->
                val name = symbol.simpleName.asString()
                val qName = symbol.qualifiedName?.asString() ?: name
                val anchor = qName.lowercase().replace(".", "")
                val displayName = if (name in duplicateNames) qName else name
                out.writeLine("    - [$displayName](#$anchor)")
            }
            out.writeLine("")

            out.writeLine("## Data Models")
            out.writeLine("")

            modelSymbols.sortedBy { it.qualifiedName?.asString() }.forEach { model ->
                generateModelDoc(out, model, documentedModels, duplicateNames)
            }

            out.writeLine("---")
            out.writeLine("## RPC Services")
            out.writeLine("")

            serviceSymbols.sortedBy { it.qualifiedName?.asString() }.forEach { symbol ->
                generateServiceDoc(out, symbol, documentedModels, duplicateNames)
            }
        }

        return (serviceSymbols + modelSymbols).filterNot { it.validate() }
    }

    private fun findProjectRoot(file: File): File {
        var current = file
        while (current.parentFile != null) {
            if (File(current, "settings.gradle.kts").exists() || File(current, "settings.gradle").exists()) {
                return current
            }
            current = current.parentFile
        }
        return file.parentFile ?: file
    }

    private fun generateModelDoc(out: OutputStream, model: KSClassDeclaration, documentedModels: Set<String>, duplicateNames: Set<String>) {
        val name = model.simpleName.asString()
        val qName = model.qualifiedName?.asString() ?: name
        val anchor = qName.lowercase().replace(".", "")
        val docAnnotation = model.annotations.find { it.shortName.asString() == "ModelDoc" }
        val description = docAnnotation?.arguments?.find { it.name?.asString() == "description" }?.value as? String ?: ""

        out.writeLine("### $name <a name=\"$anchor\"></a>")
        if (name in duplicateNames) {
            out.writeLine("*Full name: `$qName`*")
            out.writeLine("")
        }
        if (description.isNotEmpty()) out.writeLine(description)
        out.writeLine("")
        
        if (model.classKind == ClassKind.ENUM_CLASS) {
            out.writeLine("| Value | Description |")
            out.writeLine("| :--- | :--- |")
            model.declarations.filterIsInstance<KSClassDeclaration>()
                .filter { it.classKind == ClassKind.ENUM_ENTRY }
                .forEach { entry ->
                    val fDoc = entry.annotations.find { it.shortName.asString() == "FieldDoc" }
                    val fDesc = fDoc?.arguments?.find { it.name?.asString() == "description" }?.value as? String ?: ""
                    out.writeLine("| `${entry.simpleName.asString()}` | $fDesc |")
                }
        } else {
            out.writeLine("| Field | Type | Description |")
            out.writeLine("| :--- | :--- | :--- |")
            model.getAllProperties().forEach { prop ->
                val pName = prop.simpleName.asString()
                val pType = prop.type.resolve().toTypeString(documentedModels)
                val fDoc = prop.annotations.find { it.shortName.asString() == "FieldDoc" }
                val fDesc = fDoc?.arguments?.find { it.name?.asString() == "description" }?.value as? String ?: ""
                out.writeLine("| `$pName` | $pType | $fDesc |")
            }
        }
        out.writeLine("")
    }

    private fun generateServiceDoc(out: OutputStream, symbol: KSClassDeclaration, documentedModels: Set<String>, duplicateNames: Set<String>) {
        val name = symbol.simpleName.asString()
        val qName = symbol.qualifiedName?.asString() ?: name
        val anchor = qName.lowercase().replace(".", "")
        val rpcDoc = symbol.annotations.find { it.shortName.asString() == "RpcDoc" }
        val serviceDesc = rpcDoc?.arguments?.find { it.name?.asString() == "description" }?.value as? String ?: ""

        out.writeLine("### $name <a name=\"$anchor\"></a>")
        if (name in duplicateNames) {
            out.writeLine("*Full name: `$qName`*")
            out.writeLine("")
        }
        if (serviceDesc.isNotEmpty()) out.writeLine(serviceDesc)
        out.writeLine("")
        
        out.writeLine("| Function | Parameters | Returns | Permissions | Errors | Description |")
        out.writeLine("| :--- | :--- | :--- | :--- | :--- | :--- |")

        symbol.getAllFunctions().filter {
            it.isPublic() && it.simpleName.asString() !in listOf("<init>", "equals", "hashCode", "toString")
        }.forEach { func ->
            val fName = func.simpleName.asString()
            val fDoc = func.annotations.find { it.shortName.asString() == "RpcDoc" }
            val desc = fDoc?.arguments?.find { it.name?.asString() == "description" }?.value as? String ?: ""
            
            val permissions = mutableListOf<String>()
            if (func.annotations.any { it.shortName.asString() == "RequiresAdmin" }) {
                permissions.add("**Admin**")
            }
            func.annotations.find { it.shortName.asString() == "RequiresCapability" }?.let { capAnn ->
                val cap = capAnn.arguments.find { it.name?.asString() == "capability" }?.value?.toString()?.split(".")?.last()
                if (cap != null) permissions.add("`$cap`")
            }
            val permissionStr = permissions.joinToString(", ").ifEmpty { "-" }

            val errors = (fDoc?.arguments?.find { it.name?.asString() == "errors" }?.value as? List<*>)?.joinToString(", ") ?: "-"
            
            val params = func.parameters.joinToString("<br>") { param ->
                val pName = param.name?.asString() ?: "arg"
                val pType = param.type.resolve().toTypeString(documentedModels)
                val pDoc = param.annotations.find { it.shortName.asString() == "RpcParamDoc" }
                val pDesc = pDoc?.arguments?.find { it.name?.asString() == "description" }?.value as? String
                if (pDesc != null) "`$pName` ($pType): $pDesc" else "`$pName` ($pType)"
            }.ifEmpty { "-" }

            val retType = func.returnType?.resolve()?.toTypeString(documentedModels) ?: "Unit"

            out.writeLine("| `$fName` | $params | $retType | $permissionStr | $errors | $desc |")
        }
        out.writeLine("")
    }

    private fun collectModels(type: KSType, set: MutableSet<KSClassDeclaration>) {
        val decl = type.declaration
        if (decl is KSClassDeclaration && (decl.classKind == ClassKind.CLASS || decl.classKind == ClassKind.ENUM_CLASS)) {
            val qName = decl.qualifiedName?.asString() ?: ""
            val isBuiltIn = qName.startsWith("kotlin.") ||
                    qName.startsWith("kotlinx.coroutines.") ||
                    qName.startsWith("dev.dertyp.Platform") ||
                    qName.startsWith("kotlinx.serialization.")

            if (!isBuiltIn && !set.contains(decl)) {
                set.add(decl)
                decl.getAllProperties().forEach { collectModels(it.type.resolve(), set) }
            }
        }
        type.arguments.forEach { argument -> argument.type?.resolve()?.let { collectModels(it, set) } }
    }

    private fun OutputStream.writeLine(str: String) = this.write((str + "\n").toByteArray())

    private fun KSType.toTypeString(documentedModels: Set<String>): String {
        val name = declaration.simpleName.asString()
        val qName = declaration.qualifiedName?.asString() ?: name
        val nullability = if (isMarkedNullable) "?" else ""

        val anchor = qName.lowercase().replace(".", "")

        val formattedName = if (qName in documentedModels) {
            "[$name](#$anchor)"
        } else {
            "`$name`"
        }

        if (arguments.isEmpty()) return "$formattedName$nullability"
        val args = arguments.joinToString(", ") { it.type?.resolve()?.toTypeString(documentedModels) ?: "Any" }
        return "$formattedName<$args>$nullability"
    }
}

class DocProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment) = 
        DocProcessor(environment.options)
}
