package dev.dertyp.rpc.doc

import com.google.devtools.ksp.isPublic
import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.validate
import java.io.File
import java.io.OutputStream

class DocProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
    private val options: Map<String, String>
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val serviceSymbols = resolver.getSymbolsWithAnnotation("dev.dertyp.rpc.annotations.RpcDoc")
            .filterIsInstance<KSClassDeclaration>()
            .toList()

        val modelSymbols = resolver.getSymbolsWithAnnotation("dev.dertyp.rpc.annotations.ModelDoc")
            .filterIsInstance<KSClassDeclaration>()
            .toList()

        if (serviceSymbols.isEmpty() && modelSymbols.isEmpty()) return emptyList()

        val anySourceFile = (serviceSymbols.firstOrNull() ?: modelSymbols.firstOrNull())?.containingFile?.filePath ?: return emptyList()

        val projectRoot = findProjectRoot(File(anySourceFile))
        
        val docPath = options["rpc.doc.path"] ?: "docs"
        val docName = options["rpc.doc.name"] ?: "RPC_SERVICES.md"
        
        val docsDir = if (docPath.startsWith("/")) File(docPath) else File(projectRoot, docPath)
        if (!docsDir.exists()) docsDir.mkdirs()
        val docFile = File(docsDir, docName)

        val documentedModels = modelSymbols.map { it.simpleName.asString() }.toSet()

        docFile.outputStream().use { out ->
            out.writeLine("# Synara RPC Services Documentation")
            out.writeLine("")
            out.writeLine("This document is automatically generated by the DocProcessor KSP.")
            out.writeLine("")

            out.writeLine("## Data Models")
            out.writeLine("")

            modelSymbols.sortedBy { it.simpleName.asString() }.forEach { model ->
                generateModelDoc(out, model, documentedModels)
            }

            out.writeLine("---")
            out.writeLine("## RPC Services")
            out.writeLine("")

            serviceSymbols.sortedBy { it.simpleName.asString() }.forEach { symbol ->
                generateServiceDoc(out, symbol, documentedModels)
            }
        }

        return (serviceSymbols + modelSymbols).filterNot { it.validate() }
    }

    private fun findProjectRoot(file: File): File {
        var current = file
        while (current.parentFile != null) {
            if (File(current, "settings.gradle.kts").exists() || File(current, "settings.gradle").exists()) {
                return current
            }
            current = current.parentFile
        }
        return file.parentFile ?: file
    }

    private fun generateModelDoc(out: OutputStream, model: KSClassDeclaration, documentedModels: Set<String>) {
        val name = model.simpleName.asString()
        val docAnnotation = model.annotations.find { it.shortName.asString() == "ModelDoc" }
        val description = docAnnotation?.arguments?.find { it.name?.asString() == "description" }?.value as? String ?: ""

        out.writeLine("### $name")
        if (description.isNotEmpty()) out.writeLine(description)
        out.writeLine("")
        
        if (model.classKind == ClassKind.ENUM_CLASS) {
            out.writeLine("| Value | Description |")
            out.writeLine("| :--- | :--- |")
            model.declarations.filterIsInstance<KSClassDeclaration>()
                .filter { it.classKind == ClassKind.ENUM_ENTRY }
                .forEach { entry ->
                    out.writeLine("| `${entry.simpleName.asString()}` | |")
                }
        } else {
            out.writeLine("| Field | Type | Description |")
            out.writeLine("| :--- | :--- | :--- |")
            model.getAllProperties().forEach { prop ->
                val pName = prop.simpleName.asString()
                val pType = prop.type.resolve().toTypeString(documentedModels)
                val fDoc = prop.annotations.find { it.shortName.asString() == "FieldDoc" }
                val fDesc = fDoc?.arguments?.find { it.name?.asString() == "description" }?.value as? String ?: ""
                out.writeLine("| `$pName` | $pType | $fDesc |")
            }
        }
        out.writeLine("")
    }

    private fun generateServiceDoc(out: OutputStream, symbol: KSClassDeclaration, documentedModels: Set<String>) {
        val name = symbol.simpleName.asString()
        val rpcDoc = symbol.annotations.find { it.shortName.asString() == "RpcDoc" }
        val serviceDesc = rpcDoc?.arguments?.find { it.name?.asString() == "description" }?.value as? String ?: ""

        out.writeLine("### $name")
        if (serviceDesc.isNotEmpty()) out.writeLine(serviceDesc)
        out.writeLine("")
        
        out.writeLine("| Function | Parameters | Returns | Admin | Errors | Description |")
        out.writeLine("| :--- | :--- | :--- | :---: | :--- | :--- |")

        symbol.getAllFunctions().filter {
            it.isPublic() && it.simpleName.asString() !in listOf("<init>", "equals", "hashCode", "toString")
        }.forEach { func ->
            val fName = func.simpleName.asString()
            val fDoc = func.annotations.find { it.shortName.asString() == "RpcDoc" }
            val desc = fDoc?.arguments?.find { it.name?.asString() == "description" }?.value as? String ?: ""
            val admin = if (fDoc?.arguments?.find { it.name?.asString() == "adminOnly" }?.value == true) "**Yes**" else "No"
            val errors = (fDoc?.arguments?.find { it.name?.asString() == "errors" }?.value as? List<*>)?.joinToString(", ") ?: "-"
            
            val params = func.parameters.joinToString("<br>") { param ->
                val pName = param.name?.asString() ?: "arg"
                val pType = param.type.resolve().toTypeString(documentedModels)
                val pDoc = param.annotations.find { it.shortName.asString() == "RpcParamDoc" }
                val pDesc = pDoc?.arguments?.find { it.name?.asString() == "description" }?.value as? String
                if (pDesc != null) "`$pName`: $pDesc" else "`$pName` ($pType)"
            }.ifEmpty { "-" }

            val retType = func.returnType?.resolve()?.toTypeString(documentedModels) ?: "Unit"

            out.writeLine("| `$fName` | $params | $retType | $admin | $errors | $desc |")
        }
        out.writeLine("")
    }

    private fun collectModels(type: KSType, set: MutableSet<KSClassDeclaration>) {
        val decl = type.declaration
        if (decl is KSClassDeclaration && (decl.classKind == ClassKind.CLASS || decl.classKind == ClassKind.ENUM_CLASS)) {
            val qName = decl.qualifiedName?.asString() ?: ""
            val isBuiltIn = qName.startsWith("kotlin.") ||
                    qName.startsWith("kotlinx.coroutines.") ||
                    qName.startsWith("dev.dertyp.Platform") ||
                    qName.startsWith("kotlinx.serialization.")

            if (!isBuiltIn && !set.contains(decl)) {
                set.add(decl)
                decl.getAllProperties().forEach { collectModels(it.type.resolve(), set) }
            }
        }
        type.arguments.forEach { argument -> argument.type?.resolve()?.let { collectModels(it, set) } }
    }

    private fun OutputStream.writeLine(str: String) = this.write((str + "\n").toByteArray())

    private fun KSType.toTypeString(documentedModels: Set<String>): String {
        val name = declaration.simpleName.asString()
        val nullability = if (isMarkedNullable) "?" else ""

        val displayName = if (name in documentedModels) {
            "[$name](#${name.lowercase()})"
        } else {
            "`$name`"
        }

        if (arguments.isEmpty()) return "$displayName$nullability"
        val args = arguments.joinToString(", ") { it.type?.resolve()?.toTypeString(documentedModels) ?: "Any" }
        return "$displayName<$args>$nullability"
    }
}

class DocProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment) = 
        DocProcessor(environment.codeGenerator, environment.logger, environment.options)
}
