@file:UseContextualSerialization(PlatformUUID::class)

package dev.dertyp.data

import dev.dertyp.PlatformUUID
import dev.dertyp.rpc.annotations.FieldDoc
import dev.dertyp.rpc.annotations.ModelDoc
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseContextualSerialization

@Serializable
@ModelDoc("The kind of entity a generated cover belongs to.")
enum class CoverTargetType {
    @FieldDoc("A user playlist.")
    PLAYLIST,
    @FieldDoc("A media collection.")
    COLLECTION
}

@Serializable
@ModelDoc("Where the current cover image of a playlist or collection came from.")
enum class ImageSource {
    @FieldDoc("Chosen or uploaded by the user; never replaced automatically.")
    USER,
    @FieldDoc("Generated by the server; may be regenerated when the content changes.")
    GENERATED
}

@Serializable
@ModelDoc("Layout style of a generated cover.")
enum class CoverStyle {
    @FieldDoc("Pick a style from the number of available source images.")
    AUTO,
    @FieldDoc("A single source image, full bleed.")
    SINGLE,
    @FieldDoc("A 2x2 grid of source images.")
    GRID,
    @FieldDoc("A 3x3 grid of source images.")
    MOSAIC,
    @FieldDoc("Overlapping, slightly rotated source images.")
    STACKED,
    @FieldDoc("No source images; a gradient derived from the content palette.")
    GRADIENT
}

@Serializable
@ModelDoc("Identifies the playlist or collection a cover operation applies to.")
data class CoverTarget(
    @FieldDoc("The kind of entity.")
    val type: CoverTargetType,
    @FieldDoc("The entity unique identifier.")
    val id: PlatformUUID,
)

@Serializable
@ModelDoc("Parameters controlling how a cover is generated.")
data class CoverGenerationParams(
    @FieldDoc("Layout style.")
    val style: CoverStyle = CoverStyle.AUTO,
    @FieldDoc("Seed for deterministic output; null derives a stable seed from the content.")
    val seed: Long? = null,
    @FieldDoc("Whether NSFW asset packs may be used. Ignored unless enabled on the server.")
    val allowNsfw: Boolean = false,
    @FieldDoc("Whether to draw the playlist or collection name on the cover.")
    val includeTitle: Boolean = true,
    @FieldDoc("Asset pack id to use; null picks the best match for the content.")
    val pack: String? = null,
)

@Serializable
@ModelDoc("An asset pack available for cover generation.")
data class CoverPackInfo(
    @FieldDoc("Pack id.")
    val id: String,
    @FieldDoc("Display name.")
    val name: String,
    @FieldDoc("Tags the pack matches against, e.g. genres, mood:*, energy:*, palette:*.")
    val tags: List<String> = emptyList(),
    @FieldDoc("Whether the pack contains adult content.")
    val nsfw: Boolean = false,
    @FieldDoc("Attribution or license note.")
    val attribution: String? = null,
)

@Serializable
@ModelDoc("Styles and asset packs the current user may choose from.")
data class CoverGenerationOptions(
    @FieldDoc("Available styles.")
    val styles: List<CoverStyle>,
    @FieldDoc("Available asset packs; NSFW packs are only listed when enabled on the server.")
    val packs: List<CoverPackInfo>,
    @FieldDoc("Whether NSFW packs are enabled on the server.")
    val nsfwEnabled: Boolean,
)

@Serializable
@ModelDoc("The current cover state of a playlist or collection.")
data class CoverInfo(
    @FieldDoc("The entity the info refers to.")
    val target: CoverTarget,
    @FieldDoc("The current cover image unique identifier.")
    val imageId: PlatformUUID? = null,
    @FieldDoc("Where the current cover came from; null when there is no cover.")
    val source: ImageSource? = null,
    @FieldDoc("Style used for the last generated cover.")
    val style: CoverStyle? = null,
    @FieldDoc("Seed used for the last generated cover.")
    val seed: Long? = null,
)
