package dev.dertyp.rpc.rest

import com.squareup.kotlinpoet.BOOLEAN
import com.squareup.kotlinpoet.BYTE_ARRAY
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LambdaTypeName
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.UNIT

private val ROUTE = ClassName("io.ktor.server.routing", "Route")
private val ROUTING_CONTEXT = ClassName("io.ktor.server.routing", "RoutingContext")
private val ROUTE_CONFIG = ClassName("io.github.smiley4.ktoropenapi.config", "RouteConfig")
private val HTTP_STATUS_CODE = ClassName("io.ktor.http", "HttpStatusCode")
private val CONTENT_TYPE = ClassName("io.ktor.http", "ContentType")
private val JSON_OBJECT = ClassName("kotlinx.serialization.json", "JsonObject")

private val ROUTE_FUNCTION = MemberName("io.ktor.server.routing", "route")
private val INSTALL = MemberName("io.ktor.server.application", "install")
private val PARTIAL_CONTENT = MemberName("io.ktor.server.plugins.partialcontent", "PartialContent")

private val VERBS = mapOf(
    "GET" to MemberName("io.github.smiley4.ktoropenapi", "get"),
    "POST" to MemberName("io.github.smiley4.ktoropenapi", "post"),
    "PUT" to MemberName("io.github.smiley4.ktoropenapi", "put"),
    "DELETE" to MemberName("io.github.smiley4.ktoropenapi", "delete")
)
private val HEAD = MemberName("io.github.smiley4.ktoropenapi", "head")

private val RESERVED_NAMES = setOf(
    "service",
    "call",
    "result",
    "defaults",
    "authenticated",
    "serviceFactory"
)

internal class LocalNames(
    private val finals: Map<RestParam, String>,
    private val raws: Map<RestParam, String>
) {
    fun final(param: RestParam): String = finals.getValue(param)

    fun raw(param: RestParam): String = raws.getValue(param)
}

class KotlinEmitter(private val restPackage: String) {

    private val capturedArguments = ClassName(restPackage, "CapturedArguments")
    private val restRoute = MemberName(restPackage, "restRoute")
    private val captureDefaults = MemberName(restPackage, "captureDefaults")

    fun emit(service: RestService): FileSpec {
        val factoryType = LambdaTypeName
            .get(receiver = ROUTING_CONTEXT, returnType = service.className)
            .copy(suspending = true)

        val register = FunSpec.builder(service.registerFunctionName)
            .receiver(ROUTE)
            .addParameter(ParameterSpec.builder("authenticated", BOOLEAN).defaultValue("false").build())
            .addParameter("serviceFactory", factoryType)
            .addCode(registerBody(service))
            .build()

        return FileSpec.builder(restPackage, service.fileName)
            .addFileComment("Generated by common-rpc/rest-compiler from %L. Do not edit.", service.qualifiedName)
            .addFunction(register)
            .addType(defaultsObject(service))
            .build()
    }

    private fun registerBody(service: RestService): CodeBlock {
        val body = CodeBlock.builder()
        body.beginControlFlow("%M(%S)", ROUTE_FUNCTION, "/${service.prefix}")
        if (service.hasFileResponse) {
            body.beginControlFlow("%M(%M)", INSTALL, PARTIAL_CONTENT)
            body.addStatement("maxRangeCount = 10")
            body.endControlFlow()
        }
        service.routes.forEach { route ->
            if (route.isFileResponse) emitFileRoute(body, service, route) else emitRoute(body, service, route)
        }
        body.endControlFlow()
        return body.build()
    }

    private fun emitRoute(body: CodeBlock.Builder, service: RestService, route: RestRoute) {
        val verb = VERBS.getValue(route.method)
        body.add("%M(%S, {\n", verb, route.localPath)
        body.indent()
        emitDoc(body, service, route)
        body.unindent()
        body.add("}) {\n")
        body.indent()
        emitHandler(body, service, route)
        body.unindent()
        body.add("}\n")
    }

    private fun emitFileRoute(body: CodeBlock.Builder, service: RestService, route: RestRoute) {
        val docName = "${route.functionName}Doc"
        val handlerName = "${route.functionName}Handler"
        val docType = LambdaTypeName.get(receiver = ROUTE_CONFIG, returnType = UNIT)
        val handlerType = LambdaTypeName.get(receiver = ROUTING_CONTEXT, returnType = UNIT).copy(suspending = true)

        body.add("val %N: %T = {\n", docName, docType)
        body.indent()
        emitDoc(body, service, route)
        body.unindent()
        body.add("}\n")

        body.add("val %N: %T = {\n", handlerName, handlerType)
        body.indent()
        emitHandler(body, service, route)
        body.unindent()
        body.add("}\n")

        body.addStatement("%M(%S, %N, %N)", HEAD, route.localPath, docName, handlerName)
        body.addStatement("%M(%S, %N, %N)", VERBS.getValue(route.method), route.localPath, docName, handlerName)
    }

    private fun emitDoc(body: CodeBlock.Builder, service: RestService, route: RestRoute) {
        body.addStatement("tags(%S)", service.prefix)
        route.summary?.let { body.addStatement("summary = %S", it) }
        body.addStatement("operationId = %S", "${service.simpleName}.${route.functionName}")
        if (!route.isPublic) body.addStatement("if (authenticated) securitySchemeNames(%S)", "UserAuth")

        body.beginControlFlow("request")
        route.params.forEach { param ->
            if (route.multiBody && param.source == ParamSource.BODY) return@forEach
            val call = when (param.source) {
                ParamSource.PATH -> CodeBlock.of("pathParameter<%T>(%S)", param.safeType, param.name)
                ParamSource.BODY -> CodeBlock.of("body<%T>", param.safeType)
                else -> CodeBlock.of("queryParameter<%T>(%S)", param.safeType, param.name)
            }
            if (param.description != null) {
                body.add("%L { description = %S }\n", call, param.description)
            } else {
                body.add("%L { }\n", call)
            }
        }
        if (route.multiBody) {
            val fields = route.params
                .filter { it.source == ParamSource.BODY }
                .joinToString(", ") { "${it.name} (${simpleTypeName(it.declaredType)})" }
            body.add(
                "body<%T> { description = %S }\n",
                JSON_OBJECT,
                "JSON object with fields: $fields"
            )
        }
        body.endControlFlow()

        body.beginControlFlow("response")
        body.beginControlFlow("%T.OK to", HTTP_STATUS_CODE)
        body.addStatement("description = %S", "Successful")
        when {
            route.isFileResponse -> {
                body.beginControlFlow("body<%T>", BYTE_ARRAY)
                body.addStatement("mediaTypes(%T.Application.OctetStream)", CONTENT_TYPE)
                body.endControlFlow()
            }
            route.isUnit -> Unit
            route.safeItemType != null -> {
                body.beginControlFlow("body<%T>", route.safeItemType)
                if (route.itemIsByteArray) {
                    body.addStatement("mediaTypes(%T.Application.OctetStream)", CONTENT_TYPE)
                } else {
                    body.addStatement("mediaTypes(%T.Text.EventStream)", CONTENT_TYPE)
                }
                body.endControlFlow()
            }
            else -> body.addStatement("body<%T>()", route.safeReturnType)
        }
        body.endControlFlow()
        route.errors.forEach { error ->
            body.addStatement("%T.InternalServerError to { description = %S }", HTTP_STATUS_CODE, error)
        }
        body.endControlFlow()
    }

    private fun emitHandler(body: CodeBlock.Builder, service: RestService, route: RestRoute) {
        val names = localNames(route)

        body.beginControlFlow(
            "%M(requireUser = %L, %T::class.java, serviceFactory)",
            restRoute,
            if (route.isPublic) "false" else "authenticated",
            service.className
        )

        route.params.forEach { param ->
            body.addStatement("val %N = %L", names.raw(param), bindExpression(route, param))
        }

        if (route.isFileResponse) {
            val arguments = route.params.joinToCode(", ") { CodeBlock.of("%N", names.raw(it)) }
            body.addStatement(
                "if (respondFile(%S, listOf(%L))) return@restRoute",
                route.functionName,
                arguments
            )
        }

        if (route.responseKind == ResponseKind.UNIT) {
            body.add("restInvoke {\n")
        } else {
            body.add("val result = restInvoke {\n")
        }
        body.indent()
        emitInvocation(body, service, route, names)
        body.unindent()
        body.add("} ?: return@restRoute\n")

        when (route.responseKind) {
            ResponseKind.UNIT -> body.addStatement("respondOk()")
            ResponseKind.JSON -> body.addStatement("respondJson(%L)", route.jsonTransform ?: CodeBlock.of("result"))
            ResponseKind.BYTES -> body.addStatement("respondBytes(result)")
            ResponseKind.BYTE_FLOW -> body.addStatement("respondBytesFlow(result)")
            ResponseKind.SSE -> {
                val itemType = if (route.sseTransform != null) route.safeItemType!! else route.sseItemType!!
                body.addStatement(
                    "respondSse<%T>(%L)",
                    itemType,
                    route.sseTransform ?: CodeBlock.of("result")
                )
            }
        }

        body.endControlFlow()
    }

    private fun emitInvocation(
        body: CodeBlock.Builder,
        service: RestService,
        route: RestRoute,
        names: LocalNames
    ) {
        route.params.filter { !it.resolvedAtDeclaration && it.required }.forEach { param ->
            body.addStatement("val %N = required(%S, %N)", names.final(param), param.name, names.raw(param))
        }

        if (route.needsProbe) {
            val probeArguments = route.params.filter { it.required }
                .joinToCode(", ") { CodeBlock.of("%N = %N", it.name, names.final(it)) }
            val condition = route.params
                .filter { !it.resolvedAtDeclaration && !it.required }
                .joinToCode(" || ") { CodeBlock.of("%N == null", names.raw(it)) }
            body.addStatement(
                "val defaults = if (%L) %M { %N.%N(%L) } else null",
                condition,
                captureDefaults,
                service.defaultsObjectName,
                route.functionName,
                probeArguments
            )
        }

        if (route.params.isEmpty()) {
            body.addStatement("service.%N()", route.functionName)
            return
        }

        body.add("service.%N(\n", route.functionName)
        body.indent()
        route.params.forEach { param ->
            val value = if (param.resolvedAtDeclaration || param.required) {
                CodeBlock.of("%N", names.final(param))
            } else {
                CodeBlock.of(
                    "%N ?: defaults!!.arg<%T>(%L)",
                    names.raw(param),
                    param.declaredType.copy(nullable = false),
                    param.index
                )
            }
            body.add("%N = %L,\n", param.name, value)
        }
        body.unindent()
        body.add(")\n")
    }

    private fun localNames(route: RestRoute): LocalNames {
        val used = mutableSetOf<String>()
        val finals = mutableMapOf<RestParam, String>()
        val raws = mutableMapOf<RestParam, String>()
        route.params.forEach { param ->
            var candidate = if (param.name in RESERVED_NAMES) "${param.name}Value" else param.name
            while (candidate in used) candidate += "_"
            used += candidate
            finals[param] = candidate
        }
        route.params.forEach { param ->
            if (param.resolvedAtDeclaration) {
                raws[param] = finals.getValue(param)
            } else {
                var candidate = "${finals.getValue(param)}Raw"
                while (candidate in used) candidate += "_"
                used += candidate
                raws[param] = candidate
            }
        }
        return LocalNames(finals, raws)
    }

    private fun simpleTypeName(type: TypeName): String = when (val plain = type.copy(nullable = false)) {
        is ClassName -> plain.simpleName
        is ParameterizedTypeName ->
            plain.rawType.simpleName + plain.typeArguments.joinToString(", ", "<", ">") { simpleTypeName(it) }
        else -> plain.toString()
    }

    private fun bindExpression(route: RestRoute, param: RestParam): CodeBlock = when (param.source) {
        ParamSource.PATH -> CodeBlock.of("pathParam(%S, %L)", param.name, param.elementConverter!!)
        ParamSource.QUERY -> CodeBlock.of("queryParam(%S, %L)", param.name, param.elementConverter!!)
        ParamSource.QUERY_LIST ->
            if (param.resolvedAtDeclaration && !param.nullable) {
                CodeBlock.of("queryList(%S, %L) ?: emptyList()", param.name, param.elementConverter!!)
            } else {
                CodeBlock.of("queryList(%S, %L)", param.name, param.elementConverter!!)
            }
        ParamSource.QUERY_SET ->
            if (param.resolvedAtDeclaration && !param.nullable) {
                CodeBlock.of("querySet(%S, %L) ?: emptySet()", param.name, param.elementConverter!!)
            } else {
                CodeBlock.of("querySet(%S, %L)", param.name, param.elementConverter!!)
            }
        ParamSource.QUERY_JSON -> CodeBlock.of(
            "queryJson<%T>(%S)",
            param.declaredType.copy(nullable = false),
            param.name
        )
        ParamSource.BODY -> {
            val required = param.required && !param.nullable
            val function = when {
                route.multiBody && required -> "receiveJsonField"
                route.multiBody -> "receiveJsonFieldOrNull"
                required -> "receiveJsonBody"
                else -> "receiveJsonBodyOrNull"
            }
            CodeBlock.of("%L<%T>(%S)", function, param.declaredType.copy(nullable = false), param.name)
        }
    }

    private fun defaultsObject(service: RestService): TypeSpec {
        val builder = TypeSpec.objectBuilder(service.defaultsObjectName)
            .addModifiers(KModifier.PRIVATE)
            .addSuperinterface(service.className)

        service.probeFunctions.forEach { function ->
            val spec = FunSpec.builder(function.name).addModifiers(KModifier.OVERRIDE)
            if (function.isSuspend) spec.addModifiers(KModifier.SUSPEND)
            function.parameters.forEach { spec.addParameter(it.first, it.second) }
            spec.returns(function.returnType)
            val arguments = function.parameters.joinToCode(", ") { CodeBlock.of("%N", it.first) }
            spec.addStatement("throw %T(%L)", capturedArguments, arguments)
            builder.addFunction(spec.build())
        }

        return builder.build()
    }
}

internal fun <T> List<T>.joinToCode(separator: String, transform: (T) -> CodeBlock): CodeBlock {
    val builder = CodeBlock.builder()
    forEachIndexed { index, element ->
        if (index > 0) builder.add(separator)
        builder.add(transform(element))
    }
    return builder.build()
}
