package dev.dertyp.rpc.rest

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.LIST
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec

class ManifestEmitter(private val restPackage: String) {

    private val routeInfo = ClassName(restPackage, "RestRouteInfo")
    private val paramInfo = ClassName(restPackage, "RestParamInfo")
    private val paramSource = ClassName(restPackage, "RestParamSource")
    private val responseKind = ClassName(restPackage, "RestResponseKind")

    fun emit(services: List<RestService>): FileSpec {
        val entries = CodeBlock.builder()
        entries.add("listOf(\n")
        entries.indent()
        services.forEach { service ->
            service.routes.forEach { route ->
                if (route.isFileResponse) entries.add(entry(service, route, "HEAD"))
                entries.add(entry(service, route, route.method))
            }
        }
        entries.unindent()
        entries.add(")")

        val manifest = PropertySpec.builder("manifest", LIST.parameterizedBy(routeInfo))
            .initializer(entries.build())
            .build()

        return FileSpec.builder(restPackage, "GeneratedRestRoutes")
            .addFileComment("Generated by common-rpc/rest-compiler. Do not edit.")
            .addType(
                TypeSpec.objectBuilder("GeneratedRestRoutes")
                    .addProperty(manifest)
                    .build()
            )
            .build()
    }

    private fun entry(service: RestService, route: RestRoute, method: String): CodeBlock {
        val params = route.params.joinToCode(", ") { param ->
            CodeBlock.of(
                "%T(%S, %T.%L, optional = %L)",
                paramInfo,
                param.name,
                paramSource,
                when (param.source) {
                    ParamSource.PATH -> "PATH"
                    ParamSource.BODY -> "BODY"
                    else -> "QUERY"
                },
                param.hasDefault
            )
        }
        val kind = if (route.isFileResponse) "FILE" else route.responseKind.name
        return CodeBlock.of(
            "%T(servicePrefix = %S, method = %S, localPath = %S, interfaceName = %S, functionName = %S, public = %L, params = listOf(%L), response = %T.%L),\n",
            routeInfo,
            service.prefix,
            method,
            route.localPath,
            service.qualifiedName,
            route.functionName,
            route.isPublic,
            params,
            responseKind,
            kind
        )
    }
}
