package dev.dertyp.rpc.rest

import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSDeclaration
import com.google.devtools.ksp.symbol.KSType
import java.io.File

private const val MODEL_DOC = "dev.dertyp.rpc.annotations.ModelDoc"
private const val RPC_DOC_ANNOTATION = "dev.dertyp.rpc.annotations.RpcDoc"
private const val REQUIRES_ADMIN = "dev.dertyp.data.RequiresAdmin"
private const val REQUIRES_CAPABILITY = "dev.dertyp.data.RequiresCapability"

class RestDocEmitter(
    private val logger: KSPLogger,
    private val options: Map<String, String>
) {

    private val documented = mutableMapOf<String, Boolean>()
    private val modelsDoc = options["rest.doc.modelsName"] ?: "MODELS.md"
    private val rpcDoc = options["rest.doc.rpcName"] ?: "RPC_SERVICES.md"
    private val guideDoc = options["rest.doc.guideName"] ?: "CLIENT_REST.md"
    private val publicPrefixes = options["rest.doc.publicServices"].orEmpty()
        .split(",")
        .map { it.trim() }
        .filter { it.isNotEmpty() }
        .toSet()

    fun emit(services: List<RestService>, fallbackSource: String?) {
        if (options["rest.doc"] == "false") return

        val sourceFile = services.firstNotNullOfOrNull { it.declaration.containingFile?.filePath } ?: fallbackSource
        if (sourceFile == null) {
            logger.warn("[rest-compiler] no containing file for any service; skipping REST documentation")
            return
        }

        val projectRoot = findProjectRoot(File(sourceFile))
        val docPath = options["rest.doc.path"] ?: "docs"
        val docName = options["rest.doc.name"] ?: "REST_API.md"
        val docsDir = if (docPath.startsWith("/")) File(docPath) else File(projectRoot, docPath)
        if (!docsDir.exists()) docsDir.mkdirs()
        val docFile = File(docsDir, docName)

        val content = render(services.filter { it.routes.isNotEmpty() }.sortedBy { it.qualifiedName })
        if (docFile.exists() && docFile.readText() == content) return
        docFile.writeText(content)
    }

    private fun findProjectRoot(file: File): File {
        var current = file
        while (current.parentFile != null) {
            if (File(current, "settings.gradle.kts").exists() || File(current, "settings.gradle").exists()) {
                return current
            }
            current = current.parentFile
        }
        return file.parentFile ?: file
    }

    private fun render(services: List<RestService>): String {
        val out = StringBuilder()

        out.line("# Synara REST API")
        out.line("")
        out.line(
            "This document is automatically generated by common-rpc/rest-compiler via " +
                "`./gradlew :server:kspKotlin`. Do not edit by hand."
        )
        out.line("")
        out.line(
            "Services: [$rpcDoc]($rpcDoc) · Models: [$modelsDoc]($modelsDoc) · " +
                "Guide: [$guideDoc]($guideDoc) · Index: [README.md](README.md)"
        )
        out.line("")

        out.line("## How to read this file")
        out.line("")
        out.line(
            "- Every route is derived from an RPC interface function; the derivation rules (method, path segment, " +
                "parameter binding) are listed in [How routes are derived](#how-routes-are-derived) below and " +
                "explained with examples in [$guideDoc]($guideDoc)."
        )
        out.line(
            "- **Parameters** lists each parameter with its binding: `path` (a path segment), `query` (a query " +
                "parameter; collections repeat the `name=` pair, objects on GET are JSON-encoded) or `body` (JSON; " +
                "when a route has several body parameters the request body is one JSON object with one field per " +
                "parameter). `optional` marks a parameter that has a default or is nullable, and the text after the " +
                "colon is its documentation."
        )
        out.line(
            "- **Response** is `JSON <type>` (a JSON body), `SSE <item type>` (Server-Sent Events, one JSON object " +
                "per `data:` line), `FILE` (served on GET and HEAD with `Accept-Ranges: bytes` and " +
                "`Content-Disposition: inline`), `BYTES` (a raw binary body) or `-` (an empty `200`)."
        )
        out.line(
            "- **Auth** is `public` (no token needed), `JWT` (an `Authorization: Bearer <token>` header or the " +
                "`synara-auth` cookie), `JWT + Admin` or `JWT + <CAPABILITY>` for a required user capability."
        )
        if (publicPrefixes.isNotEmpty()) {
            out.line(
                "- The " + publicPrefixes.joinToString(", ") { "`$it`" } + " services are mounted without requiring " +
                    "a user, so all of their routes are reachable without a token and are listed as `public` here."
            )
        }
        out.line("- Errors are returned as a plain-text body with status `400`, `401`, `403`, `404` or `500`.")
        out.line("")

        renderDerivationRules(out)

        out.line("## Table of Contents")
        services.forEach { service ->
            out.line("- [/${service.prefix} (${service.simpleName})](#${anchorOf(service.qualifiedName)})")
        }
        out.line("")

        services.forEach { service -> renderService(out, service) }

        return out.toString()
    }

    private fun renderDerivationRules(out: StringBuilder) {
        out.line("## How routes are derived")
        out.line("")
        out.line(
            "Nothing on this page is written by hand: every route below is derived from one function of an RPC " +
                "service interface by the same rules the server's routing code is generated with."
        )
        out.line("")
        out.line(
            "**Service prefix.** The interface name without a leading `I` and a trailing `Service`, with the first " +
                "letter lowercased: `ISongService` is mounted at `/song`, `IPodcastService` at `/podcast`."
        )
        out.line("")
        out.line(
            "**Verb and path segment.** They follow the function name. The first matching rule wins, and a prefix " +
                "only matches as a whole word — the character after it must be an upper-case letter or a digit, or " +
                "the name must be exactly the prefix. The segment keeps the name with its first letter lowercased."
        )
        out.line("")
        out.line("| Method name starts with | Verb | Segment |")
        out.line("| :--- | :--- | :--- |")
        RestRules.nameRules.forEach { rule ->
            val name = when (rule.match) {
                RuleMatch.PREFIX_WORD -> "`${rule.token}`"
                RuleMatch.INFIX -> "anything containing `${rule.token}`"
            }
            val segment = if (rule.stripPrefix) "the name without the prefix" else "the whole name"
            out.line("| $name | `${rule.method}` | $segment |")
        }
        out.line("| anything else | `${RestRules.DEFAULT_METHOD}` | the whole name |")
        out.line("")
        out.line(
            "**Explicit overrides.** `@RestGet`, `@RestPost`, `@RestPut` and `@RestDelete` on the function replace " +
                "the derived verb; `@RestPath(\"segment\")` replaces the derived segment."
        )
        out.line("")
        out.line(
            "**Path parameters.** A parameter named `type` that is primitive, not nullable and has no default " +
                "becomes a leading `{type}` segment. The first parameter named `id` or ending in `Id` that is " +
                "primitive, not nullable and has no default becomes a trailing `{name}` segment. Every other " +
                "parameter binds by its type and the route's verb."
        )
        out.line("")
        out.line("| Parameter | Bound as |")
        out.line("| :--- | :--- |")
        out.line("| a path parameter (`type` or the id, see above) | a path segment |")
        out.line("| a primitive | a query parameter |")
        out.line(
            "| a `List` or `Set` of primitives | repeated query values (`name=a&name=b`; one comma-separated " +
                "value is also accepted) |"
        )
        out.line("| a non-primitive on a `GET` route | a JSON-encoded query value |")
        out.line("| a non-primitive on a `POST`, `PUT` or `DELETE` route | the JSON request body |")
        out.line("| several body parameters | one JSON object with one field per parameter |")
        out.line("")
        out.line("**Response.** The return type decides how the body is written.")
        out.line("")
        out.line("| Return type | Response |")
        out.line("| :--- | :--- |")
        out.line("| `Flow<ByteArray>` | a byte stream |")
        out.line(
            "| anything annotated `@RestFileResponse` | served on `GET` and `HEAD` with `Accept-Ranges: bytes` |"
        )
        out.line("| another `Flow<T>` | SSE, one JSON item per `data:` line |")
        out.line("| `ByteArray` | raw bytes |")
        out.line("| `Unit` | an empty `200` |")
        out.line("| anything else | a JSON body |")
        out.line("")
    }

    private fun renderService(out: StringBuilder, service: RestService) {
        val anchor = anchorOf(service.qualifiedName)
        out.line("### /${service.prefix} — ${service.simpleName} <a name=\"$anchor\"></a>")
        val description = service.declaration.annotation(RPC_DOC_ANNOTATION)?.argument("description") as? String
        if (!description.isNullOrEmpty()) {
            out.line("")
            out.line(description)
        }
        out.line("")
        out.line("RPC reference: [${service.simpleName}]($rpcDoc#$anchor)")
        out.line("")
        out.line("| Method | Path | Parameters | Response | Auth | Description |")
        out.line("| :--- | :--- | :--- | :--- | :--- | :--- |")

        service.routes.sortedWith(compareBy({ it.localPath }, { it.method })).forEach { route ->
            val method = if (route.isFileResponse) "GET, HEAD" else route.method
            val path = "/${service.prefix}/${route.localPath}"
            val summary = route.summary?.takeIf { it.isNotEmpty() }?.let { cell(it) } ?: "-"
            val description = "$summary ([${route.functionName}]($rpcDoc#$anchor))"
            out.line(
                "| $method | `$path` | ${parameters(route)} | ${response(route)} | ${auth(service, route)} | " +
                    "$description |"
            )
        }
        out.line("")
    }

    private fun parameters(route: RestRoute): String = route.params.joinToString("<br>") { param ->
        val type = route.function.parameters.getOrNull(param.index)?.type?.resolve()
        val rendered = type?.let { typeString(it) } ?: simpleNames(param.declaredType.toString())
        val optional = if (param.hasDefault || param.nullable) ", optional" else ""
        val text = "`${param.name}` (${binding(param.source)}, $rendered$optional)"
        param.description?.takeIf { it.isNotEmpty() }?.let { "$text: ${cell(it)}" } ?: text
    }.ifEmpty { "-" }

    private fun binding(source: ParamSource): String = when (source) {
        ParamSource.PATH -> "path"
        ParamSource.QUERY -> "query"
        ParamSource.QUERY_LIST, ParamSource.QUERY_SET -> "query, repeated"
        ParamSource.QUERY_JSON -> "query, JSON"
        ParamSource.BODY -> "body"
    }

    private fun response(route: RestRoute): String {
        if (route.isFileResponse) return "FILE"
        val returnType = route.function.returnType?.resolve()
        return when (route.responseKind) {
            ResponseKind.UNIT -> "-"
            ResponseKind.BYTES, ResponseKind.BYTE_FLOW -> "BYTES"
            ResponseKind.SSE -> {
                val item = returnType?.arguments?.firstOrNull()?.type?.resolve()
                val rendered = item?.let { typeString(it) } ?: route.sseItemType?.toString()?.let { simpleNames(it) }
                if (rendered == null) "SSE" else "SSE $rendered"
            }

            ResponseKind.JSON -> {
                val rendered = returnType?.let { typeString(it) } ?: simpleNames(route.declaredReturnType.toString())
                "JSON $rendered"
            }
        }
    }

    private fun auth(service: RestService, route: RestRoute): String {
        if (route.isPublic || service.prefix in publicPrefixes) return "public"
        if (route.function.hasAnnotation(REQUIRES_ADMIN)) return "JWT + Admin"
        val capability = route.function.annotation(REQUIRES_CAPABILITY)
            ?.argument("capability")
            ?.toString()
            ?.substringAfterLast(".")
        return if (capability.isNullOrEmpty()) "JWT" else "JWT + $capability"
    }

    private fun typeString(type: KSType): String {
        val declaration = type.declaration
        val name = declaration.simpleName.asString()
        val formatted = if (isDocumented(declaration)) {
            "[$name]($modelsDoc#${anchorOf(declaration.qualifiedName?.asString() ?: name)})"
        } else {
            "`$name`"
        }
        val nullability = if (type.isMarkedNullable) "?" else ""
        if (type.arguments.isEmpty()) return "$formatted$nullability"
        val arguments = type.arguments.joinToString(", ") { argument ->
            argument.type?.resolve()?.let { typeString(it) } ?: "`*`"
        }
        return "$formatted&lt;$arguments&gt;$nullability"
    }

    private fun isDocumented(declaration: KSDeclaration): Boolean {
        val qualified = declaration.qualifiedName?.asString() ?: return false
        return documented.getOrPut(qualified) { declaration.hasAnnotation(MODEL_DOC) }
    }

    private fun simpleNames(type: String): String =
        type.replace(Regex("\\b[a-z][a-zA-Z0-9_]*(\\.[a-z][a-zA-Z0-9_]*)*\\.(?=[A-Z])"), "")
            .replace("<", "&lt;")
            .replace(">", "&gt;")

    private fun cell(text: String): String = text.replace("|", "\\|").replace("\n", " ")

    private fun anchorOf(qualifiedName: String): String = qualifiedName.lowercase().replace(".", "")

    private fun StringBuilder.line(text: String) {
        append(text).append("\n")
    }
}
